### ISSUE TITLE
乐子大神🤣

### ISSUE THREAD

**Issue by xjh2009** [nkxingxh/gamelan-website#1]
大神主打一个神权
群里一堆舔狗🤣
说不过就神权
自己违反了开源协议就红温了😂
等一会是不是要把我IssuesClose掉😋

**Comment by xjh2009** [comment]
小学生又精神胜利了捏😋

**Comment by nkxingxh** [comment]
如果你无法给出具体证据以及依据，将当作spam处理。

**Comment by xjh2009** [comment]
![1719148746631](https://github.com/nkxingxh/gamelan-website/assets/102580788/d28d9b8d-15c6-415e-824a-fd31a98cd72e)
继上文

**Comment by nkxingxh** [comment]
建议这位Github用户了解一下隔离和非隔离。联机助手通过进程间通信与n2n交互，属于隔离方式，不被视为派生作品。

**Comment by xjh2009** [comment]
如果你觉得对 那么BakaXL 这种启动器宣传视频也是属于传播正版了捏 启动器java启动jar属于隔离方式 不属于传播盗版捏😋

**Comment by nkxingxh** [comment]
1. 这里讨论GameLan联机助手相关问题，请不要转移话题
2. 你的观点“那么BakaXL 这种启动器宣传视频也是属于传播正版了捏 启动器java启动jar属于隔离方式 不属于传播盗版捏😋”是在偷换概念。当前讨论的是GPLv3开源协议相关问题，你这句话中讨论的显然不是同一个概念。

我们欢迎理智、客观的讨论。
